name: MinigamesGUI
version: '1.0'
main: rip.shuka.minigamesGui.MinigamesGUI
api-version: '1.21'
authors: [ Shukaaa ]
website: shuka.rip
commands:
  minigame:
    description: Minigames Command
    usage: /<command>
    permission: minigame.command
    aliases: [ mg ]